# Generated by Django 5.1.1 on 2024-11-29 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='project.category'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'Category_Name'), name='unique_category_per_user'),
        ),
    ]
