# Generated by Django 5.1.1 on 2024-12-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_transaction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Category_Name',
            field=models.CharField(max_length=64),
        ),
    ]
